blueprint:
  name: Easy Customizable Controller Automation Blueprint for Hue Dimmer Switch in Zigbee2MQTT
  description: Controller automation for easy customizable Buttons with Philips Hue Dimmer Switch.
  domain: automation
  input:
    controller:
      name: (Zigbee2MQTT) Controller Name
      description: The name of the controller/Dimmer-Switch in Zigbee2MQTT (Not the name of your Home-Assistent Entity)
      default: ""
    base_topic:
      name: Root/Base mqtt topic from Zigbee2MQTT
      description: The Root/base topic as configured in Zigbee2MQTT
      default: zigbee2mqtt
    on_released:
      name: Button On released
      description: Action set to run, when the Button On is released.
      default: []
      selector:
        action: {}
    up_released:
      name: Up released
      description: Action set to run, when the Up is released.
      default: []
      selector:
        action: {}
    down_released:
      name: Down released
      description: Action set to run, when the Down is released.
      default: []
      selector:
        action: {}
    off_released:
      name: Off released
      description: Action set to run, when the Off is released.
      default: []
      selector:
        action: {}
    on_held:
      name: Button On Held
      description: Action set to run, when the Button On is held.
      default: []
      selector:
        action: {}
    up_held:
      name: Up Held
      description: Action set to run, when the Up is held.
      default: []
      selector:
        action: {}
    down_held:
      name: Down Held
      description: Action set to run, when the Down is held.
      default: []
      selector:
        action: {}
    off_held:
      name: Off Held
      description: Action set to run, when the Off is held.
      default: []
      selector:
        action: {}
mode: parallel
max: 6
trigger_variables:
  base_topic: !input base_topic
  controller: !input controller
trigger:
  - platform: mqtt
    topic: "{{ base_topic ~ '/' ~ controller }}"
action:
  - variables:
      controller: !input controller
  - choose:
      - conditions: "{{('hold' in trigger.payload_json.action) or ('release' in trigger.payload_json.action)}}"
        sequence:
          - choose:
              - conditions: '{{ trigger.payload_json.action == "on_press_release" }}'
                sequence: !input on_released
              - conditions: '{{ trigger.payload_json.action == "up_press_release" }}'
                sequence: !input up_released
              - conditions: '{{ trigger.payload_json.action == "down_press_release" }}'
                sequence: !input down_released
              - conditions: '{{ trigger.payload_json.action == "off_press_release" }}'
                sequence: !input off_released
              - conditions: '{{ trigger.payload_json.action == "on_hold" }}'
                sequence: !input on_held
              - conditions: '{{ trigger.payload_json.action == "up_hold" }}'
                sequence: !input up_held
              - conditions: '{{ trigger.payload_json.action == "down_hold" }}'
                sequence: !input down_held
              - conditions: '{{ trigger.payload_json.action == "off_hold" }}'
                sequence: !input off_held
